# Generated by Django 5.0.4 on 2024-05-18 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_grade_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='week',
            field=models.IntegerField(verbose_name='неделя'),
        ),
    ]
