# Generated by Django 5.0.4 on 2024-05-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_customuser_email_remove_customuser_kyrs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='week',
        ),
        migrations.AddField(
            model_name='grade',
            name='week1',
            field=models.IntegerField(blank=True, null=True, verbose_name='неделя1'),
        ),
        migrations.AddField(
            model_name='grade',
            name='week10',
            field=models.IntegerField(blank=True, null=True, verbose_name='неделя10'),
        ),
        migrations.AddField(
            model_name='grade',
            name='week11',
            field=models.IntegerField(blank=True, null=True, verbose_name='неделя11'),
        ),
        migrations.AddField(
            model_name='grade',
            name='week12',
            field=models.IntegerField(blank=True, null=True, verbose_name='неделя12'),
        ),
        migrations.AddField(
            model_name='grade',
            name='week13',
            field=models.IntegerField(blank=True, null=True, verbose_name='неделя13'),
        ),
        migrations.AddField(
            model_name='grade',
            name='week14',
            field=models.IntegerField(blank=True, null=True, verbose_name='неделя14'),
        ),
        migrations.AddField(
            model_name='grade',
            name='week15',
            field=models.IntegerField(blank=True, null=True, verbose_name='неделя15'),
        ),
        migrations.AddField(
            model_name='grade',
            name='week2',
            field=models.IntegerField(blank=True, null=True, verbose_name='неделя2'),
        ),
        migrations.AddField(
            model_name='grade',
            name='week3',
            field=models.IntegerField(blank=True, null=True, verbose_name='неделя3'),
        ),
        migrations.AddField(
            model_name='grade',
            name='week4',
            field=models.IntegerField(blank=True, null=True, verbose_name='неделя4'),
        ),
        migrations.AddField(
            model_name='grade',
            name='week5',
            field=models.IntegerField(blank=True, null=True, verbose_name='неделя5'),
        ),
        migrations.AddField(
            model_name='grade',
            name='week6',
            field=models.IntegerField(blank=True, null=True, verbose_name='неделя6'),
        ),
        migrations.AddField(
            model_name='grade',
            name='week7',
            field=models.IntegerField(blank=True, null=True, verbose_name='неделя7'),
        ),
        migrations.AddField(
            model_name='grade',
            name='week8',
            field=models.IntegerField(blank=True, null=True, verbose_name='неделя8'),
        ),
        migrations.AddField(
            model_name='grade',
            name='week9',
            field=models.IntegerField(blank=True, null=True, verbose_name='неделя9'),
        ),
    ]
