# Generated by Django 5.0.4 on 2024-05-18 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_grade_week_grade_week1_grade_week10_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='grade',
        ),
    ]
