# Generated by Django 5.0.4 on 2024-05-19 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_grade_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sabak_toby',
            name='sabak',
        ),
        migrations.RemoveField(
            model_name='sabak_toby',
            name='toby',
        ),
        migrations.CreateModel(
            name='Sabak_teacher_toby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sabak')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('toby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.toby')),
            ],
        ),
        migrations.DeleteModel(
            name='Sabak_teacher',
        ),
        migrations.DeleteModel(
            name='Sabak_toby',
        ),
    ]
