# Generated by Django 5.0.4 on 2024-05-23 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_sabak_toby_sabak_remove_sabak_toby_toby_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toby_kurator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.toby')),
            ],
        ),
        migrations.DeleteModel(
            name='Sabak_tury',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='week1',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='week10',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='week11',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='week12',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='week13',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='week14',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='week15',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='week2',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='week3',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='week4',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='week5',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='week6',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='week7',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='week8',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='week9',
        ),
        migrations.AddField(
            model_name='grade',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='grade',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.toby'),
        ),
        migrations.AddField(
            model_name='grade',
            name='week',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sabak',
            field=models.ManyToManyField(related_name='custom_user_sabaks', to='main.kyrs', verbose_name='sabak'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grade',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='given_grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='toby_kurator',
            name='kurator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
