# Generated by Django 5.0.4 on 2024-05-23 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_toby_kurator_delete_sabak_tury_remove_grade_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='sabak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sabak'),
        ),
    ]
