# Generated by Django 5.0.2 on 2024-05-26 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_grade_sabak'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sabak_turu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
        ),
        migrations.AddField(
            model_name='sabak_teacher_toby',
            name='sabak_turu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sabaks', to='main.toby'),
        ),
        migrations.AlterField(
            model_name='sabak_teacher_toby',
            name='toby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='main.toby'),
        ),
        migrations.CreateModel(
            name='Sabak_lek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lek', models.FileField(upload_to='documents/')),
                ('week', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.toby')),
                ('sabak', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sabak')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sabaks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
