# Generated by Django 5.0.2 on 2024-05-26 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_sabak_turu_sabak_teacher_toby_sabak_turu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sabak_teacher_toby',
            name='sabak_turu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sabaks', to='main.sabak_turu'),
        ),
    ]
