# Generated by Django 5.2 on 2025-05-11 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_week_alter_grade_week_alter_sabak_lek_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rate',
            field=models.DecimalField(blank=True, choices=[(1.0, 'Толық'), (0.5, '0.5'), (0.25, '0.25')], decimal_places=2, default=1.0, max_digits=3, null=True, verbose_name='Ставка'),
        ),
        migrations.CreateModel(
            name='Workload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lectures', models.PositiveIntegerField(default=0)),
                ('practices', models.PositiveIntegerField(default=0)),
                ('tests', models.PositiveIntegerField(default=0)),
                ('teacher', models.ForeignKey(limit_choices_to={'is_teacher': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
