# Generated by Django 5.2 on 2025-05-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_customuser_rate_workload'),
    ]

    operations = [
        migrations.AddField(
            model_name='workload',
            name='rate',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
