# Generated by Django 5.2 on 2025-05-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_workload_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workload',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
