# Generated by Django 5.2 on 2025-05-11 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_workload_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zhukteme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lectures', models.PositiveIntegerField(default=0)),
                ('practices', models.PositiveIntegerField(default=0)),
                ('tests', models.PositiveIntegerField(default=0)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('zhalaqy', models.PositiveIntegerField(default=0)),
                ('teacher', models.ForeignKey(limit_choices_to={'is_teacher': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Workload',
        ),
    ]
